
	('REUTERS/Jorge Duenes','A view shows the Toyota Motor Manufacturing plant in Tijuana, Mexico May 31, 2019. Picture taken May 31, 2019.',1,1),
	('REUTERS/Mike Blake','The front grill logo of a Ford pickup truck is seen in this photo taken in Carlsbad, California November 5, 2014',2,2),
	('REUTERS/Henry Romero','A production line is seen after the opening of Honda new automobile plant in a suburb of Celaya, Guanajuato February 21, 2014',3,3),
	('REUTERS/Rebecca Cook','An American flag flies in front of the United Auto Workers union logo on the front of the UAW Solidarity House in Detroit, Michigan, September 8, 2011.',4,4),
	('REUTERS/Mike Blake','Automobiles are shown for sale at a car dealership in Carlsbad, California, U.S. May 2, 2016.',5,5),
	('REUTERS/Anushree Fadnavis','The logo is seen on the bonnet of a new Ford Aspire car during its launch in New Delhi, India, October 4, 2018. Picture taken October 4, 2018',6,6),
	('REUTERS/Rebecca Cook','The GM logo is seen at the General Motors Warren Transmission Operations Plant in Warren, Michigan October 26, 2015',7,7),
	('REUTERS/Alessandro Bianchi','Employees of Fiat SpA work on new car "Panda" at the Fiat plant in Pomigliano DArco, near Naples, Italy, December 14, 2011.',8,8),
	('Harry Porters','The coronavirus outbreak has had a severe impact on demand for air travel',10,9),
	('Wikimedia Commons','An Air Deccan Beecraft 1900D. The original incarnation of Air Deccan was India’s largest low-cost carrier.',11,10),
	('Fact Set CNBC data','Oil future Crash',12,11),
	('FactSet','West Texas Intermediate drop into negative territory',13,11),
	('Michael Heiman','An offshore oil platform is seen with a tanker in the distance on April 20, 2020 in Huntington Beach, California.',14,12),
	('Haidar Mohammed Ali','An Iraqi labourer works at an oil refinery in the southern town Nasiriyah.',15,13),
	('Will Lester','Inland Valley Daily Bulletin',16,14),
	('USA Labor Dept','Unemployment by States',19,16),
	('CNBC','Florida is the slowest at processing unemployment claims',17,16),
	('Bloomberg/Mark Kauzlarich','A pedestrian wearing a protective mask stands outside a JPMorgan Chase & Co. bank branch in New York, U.S., on Friday, April 10, 2020',20,17),
	('BBC','Inside the almost deserted Heathrow airport',20,9),
	('PA Sport','Manchester United co-chairman Avram Glazer (right) pictured at a match at Old Trafford',22,18),
	('PA Sport','Manchester United co-chairman Avram Glazer (right) pictured at a match at Old Trafford',22,1021),
	('Reuters/Ed Syke','Soccer Football - Premier League - West Bromwich Albion vs Burnley - The Hawthorns,',23,1005),
	('Reuters','Phil Neville in England training',24,1006),
	('Getty Images','Steph Houghton of England misses a penalty during the 2019 FIFA Women World Cup France',25,1006),
	('Cameron Spencer Getty Images','Roger Federer raised the prospect of merging the ATP and WTA, the governing bodies that oversee the mens and womens tennis tours',26,1007),
	('Bertrand Rindoff Petroff/Getty Images','Defending French Open champions Rafael Nadal and Simona Halep were among the tennis players who supported Roger Federer call to join the ATP and WTA tours',27 ,1007),
	('AP Photo/Francisco Seco','Andy Murray has struggled to regain his form since early 2019 when he underwent hip surgery',28,1008),
	('Alex Davidson/Getty Images','The announcement on April 1 that Wimbledon would not be played in 2020, while well communicated and thought out, still came as a shock to many',29,1009),
	INSERT INTO DNBC_PostCollection(Source,Title,CollectionID,PostID) values
	('Getty Images','Matt Richie',81,18),('Getty Images','Matt Richie',81,1021),('Getty Images','Matt Richie',81,1022),
	('Getty Images','Jadon Sancho with Borussia Dortmund',82,18),('Getty Images','Jadon Sancho with Borussia Dortmund',82,1021),('Getty Images','Jadon Sancho with Borussia Dortmund',82,1022),('Getty Images','Jadon Sancho with Borussia Dortmund',82,1023),
	('KARIM JAAFAR/AFP via Getty Images','Petra Kvitova was on her way to Indian Wells when the tournament was canceled on March 8.',83,1009),
	
	('WILL OLIVER/EPA-EFE/Shutterstock','The All England Club sent defending champion Simona Halep an email after canceling Wimbledon, explaining the decision.',84,1009),
	('WILL OLIVER/EPA-EFE/Shutterstock','The All England Club sent defending champion Simona Halep an email after canceling Wimbledon, explaining the decision.',86,1044),
	('WILL OLIVER/EPA-EFE/Shutterstock','The All England Club sent defending champion Simona Halep an email after canceling Wimbledon, explaining the decision.',86,1045),
	('WILL OLIVER/EPA-EFE/Shutterstock','The All England Club sent defending champion Simona Halep an email after canceling Wimbledon, explaining the decision.',86,1046),
	('WILL OLIVER/EPA-EFE/Shutterstock','The All England Club sent defending champion Simona Halep an email after canceling Wimbledon, explaining the decision.',86,1047),
	('WILL OLIVER/EPA-EFE/Shutterstock','The All England Club sent defending champion Simona Halep an email after canceling Wimbledon, explaining the decision.',86,1048),
	
	('','Emergency workers searched through the foam for the missing surfers.',87,1010),
	('','Relatives, friends and the surf community gather on The Hague Beach to mourn the loss of five surfers.',88,1010),
	('AP Photo/Wong Maye-E','A man covers his mouth with a fifty dollar bill at the Speakers Corner in Singapore',89,1011),
	('AP Photo/Ng Han Guan','Supporters of the ruling People’s Action Party celebrate in Singapore, Sept. 12, 2015.',91,1011),
	('BBC','Diplomats are defending China handling of the coronavirus outbreak',92,1013),('Gurinder Osan/AP','Chinese army officers stand on China’s side of the border with India at Nathu La Pass, in northeastern Indian state of Sikkim.',94,1014),
	('Diptendu Dutta/AFP/Getty Images','This 2008 image shows a Chinese soldier and an Indian soldier at the Nathu La border crossing',95,1014),
	('Anadolu Agency/Getty Images','Imran Khan addresses Pakistan after the shooting down of an Indian fighter jet',96,1015),
	INSERT INTO DNBC_PostCollection(Source,Title,CollectionID,PostID) values
	('','Map',97,1015),('Frank Augstein/AP','Chancellor Rishi Sunak has said a levelling-up agenda must take priority over balancing the books',98,1022),(' ','Chancellor Rishi Sunak has said a levelling-up agenda must take priority over balancing the books',98,1023),
	('Opinium interviewed 2,007 UK adults from 13 to 14 May 2020','Guardian graphic.',99,1023),('Opinium interviewed 2,007 UK adults from 13 to 14 May 2020','Guardian graphic.',99,1024),('Opinium interviewed 2,007 UK adults from 13 to 14 May 2020','Guardian graphic.',99,1025),
	('Opinium interviewed 2,007 UK adults from 13 to 14 May 2020','Guardian graphic.',99,1026),('Opinium interviewed 2,007 UK adults from 13 to 14 May 2020','Guardian graphic.',99,1027),
	('Kirsty Wigglesworth','A pedestrian passes a sale sign on a closed shop on Oxford Street in London during the coronavirus pandemic.',100,1024),
	('Xinhua/Rex Shutterstock','In addition to the economic worries caused by the pandemic, many prospective buyers may have changed their ideas about where they would like to live after lockdown',101,1025),
	('Stefan Rousseau/PA','Sir James Dyson is an inventor and entrepreneur.',102,1026),('Stefan Nick Ansell/PA','About 5% of those in the bottom fifth of earners had been laid off, alongside the 25% now on the Treasury’s furlough scheme.',103,1027),
	('Vitsenko/Alamy','n the UK, Netflix is the market-leading streaming service with 12.4m subscribers. ',104,1028),
	('AP','Clockwise from top left: Netflix HQ in Los Gatos, California; The Crown; Stranger Things; and Orange is the New Black. ',105,1028),
	('AP Photo/Ng Han Guan','Supporters of the ruling People’s Action Party celebrate in Singapore, Sept. 12, 2015.',106,1029),
	('Manan Vatsyayana/AFP via Getty Images','Children wearing face masks wait to be tested as they return to a school in Hanoi',107,1030),
	('Chaideer Mahyuddin/AFP via Getty Images','A woman puts on face mask to protect against coronavirus, in Banda Aceh, Indonesia',108,1031),
	('Chaideer Anadolu Agency/Anadolu','Election officials count ballots at a polling station during the general election in South Korea',109,1032),
	('Roman Pilipey/EPA','A worker in a protective outfit checks health QR codes of a man at the entrance of a shopping mall in Wuhan',110,1033),
	
	('Fandy Azlan/Department of Information','File photo of a Parliament House session in Kuala Lumpur.',111,1034),
	('Reuters/Valentyn Ogirenko','Du Wei speaks during a news briefing in Kiev, Ukraine, Aug 30, 2019.',112,1035),
	('Reuters/Nir Elias','People and Israeli police are seen at the door of China ambassador to Israel, Du Wes home in Herzliya, near Tel Aviv, Israel',113,1035),
	('Reuters/Aly Song','Residents wearing face masks queue for nucleic acid testings in Wuhan, the Chinese city hit hardest by the COVID-19 outbreak',115,1035),
	('Reuters/Aly Song','A child reacts while undergoing nucleic acid testing in Wuhan, the Chinese city hit hardest by the COVID-19 outbreak',116,1036),
	('Reuters/Aly Song','A child reacts while undergoing nucleic acid testing in Wuhan, the Chinese city hit hardest by the COVID-19 outbreak',116,1037),
	('Reuters/Aly Song','A child reacts while undergoing nucleic acid testing in Wuhan, the Chinese city hit hardest by the COVID-19 outbreak',116,1038),
	('Reuters/Aly Song','A child reacts while undergoing nucleic acid testing in Wuhan, the Chinese city hit hardest by the COVID-19 outbreak',117,1037),
	('REUTERS/Ann Wang','Taiwan Health Minister Chen Shih-chung holds a news conference about Taiwan efforts to get into the World Health Organization (WHO)',118,1038),
	('Vitsenko/Alamy','Boris Johnson has sold his London home',119,1039),
	('Vitsenko/Alamy','The superyacht was completed in 2014.',120,1040),	('Vitsenko/Alamy','The superyacht was completed in 2014.',120,1041),
	('REUTERS/Susana Vera','A demonstrator wearing a protective face mask carries a pot during a protest against the Spanish government handling of the coronavirus disease',121,1042),
	('Reuters/Costas Baltas','Orthodox faithful respect social distancing as they attend the first service following the easing of measures against the spread of COVID-19',122,1043),
	('Reuters/Costas Baltas','Orthodox faithful respect social distancing as they attend the first service following the easing of measures against the spread of COVID-19',123,1043),
	('Alex Davidson/Getty Images','Cologne, looking for their fourth straight league win, thought they had wrapped up the match played without spectators after early goals in each half.',124,1044),
	('REUTERS/Daniele Mascolo','AC Milan Rafael Leao in action with Inter Milan Nicolo Barella during a Serie A match on Sep 21, 2019.',125,1045),
	('REUTERS/Daniele Mascolo','Pione Sisto joined Celta Vigo in 2016.',126,1046),
	('ARIM JAAFAR/AFP via Getty Images','Petra Kvitova was on her way to Indian Wells when the tournament was canceled on March 8.',127,1047),
	('AFP/GABRIEL BOUYS','Andy Murrays last Grand Slam win was his 2016 Wimbledon victory',128,1048),
	('Fact Set CNBC data','Oil future Crash',132,1018),

	INSERT INTO DNBC_PostCollection(Source,Title,CollectionID,PostID) values
	('V. M., Dyfed','British Gas sent in the debt collectors to bully a former customer over a small electricity payment.',136,1017)

	delete DNBC_PostCollection where CollectionID like 12 and PostID like 1017

	select * from DNBC_PostCollection