Insert into DNBC_Comments(Avatar,UserName, UserEmail,CommentContent,PostID ) values
('imgs/commentAvar_01.jpg','Elizabeth','eliz.@gmail.com','This article is great',1023),
('imgs/commentAvar_02.jpg','Elizabeth','eliz.@gmail.com','This article is great',1029),
('imgs/commentAvar_03.jpg','Linda E.','eliz.@gmail.com','This article is great',1040),
('imgs/commentAvar_01.jpg','Nobunaga','eliz.@gmail.com','This article is great',1036),
('imgs/commentAvar_01.jpg','Shise Narumi','eliz.@gmail.com','This article is great',1009),
('imgs/commentAvar_01.jpg','Answoth','eliz.@gmail.com','This article is great',1044),
('imgs/commentAvar_01.jpg','Ruth','eliz.@yahoo.com','This article is great',1041),
('imgs/commentAvar_01.jpg','Ruth','eliz.@yahoo.com','This article is great',4),
('imgs/commentAvar_02.jpg','Lady Gaga','Lady092@yahoo.com','I love this article. thank you',11),
('imgs/commentAvar_02.jpg','Lady Gaga','Lady092@yahoo.com','I love this article. thank you',16),
('imgs/commentAvar_02.jpg','Lady Gaga','Lady092@yahoo.com','I love this article. thank you',1028),
('imgs/commentAvar_02.jpg','Lady Gaga','Lady092@yahoo.com','I love this article. thank you',10),
('imgs/commentAvar_02.jpg','Lady Gaga','Lady092@yahoo.com','I love this article. thank you',1009),
('imgs/commentAvar_02.jpg','Lady Gaga','Lady092@yahoo.com','I love this article. thank you',1029),
('imgs/commentAvar_02.jpg','Lady Gaga','Lady092@yahoo.com','I love this article. thank you',1023),
('imgs/commentAvar_02.jpg','Lady Gaga','Lady092@yahoo.com','I love this article. thank you',1019),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',1029),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',1023),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',1040),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',1036),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',1022),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',1009),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',1019),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',1014),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',1044),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',10),
('imgs/commentAvar_03.jpg','Boys','fwf_2@gmail.com','very informative. thanks you',11);

select * from DNBC_Posts order by PostDateTime DESC;